### ISSUE TITLE
[Participant] 연관관계 수정 작업

### ISSUE THREAD

**Issue by DongGeon0908** [jung-dam-diary/team-angelbaby-jungdam-be#136]
## 📑 작업 사항 

- Diary 연관관계 수정 진행
- Comment 연관관계 수정 진행
- Emoji 연관관계 수정 진행
- Participant 연관관계 수정 진행

**Comment by DongGeon0908** [comment]
나는 할 수 있다....

**Comment by soo5717** [comment]
> 나는 할 수 있다....

할 수 있다..! 🔥🔥🔥🔥
